### ISSUE TITLE
Updates to Interim Website - Aug 24

### ISSUE THREAD

**Issue by 0xgraciegrace** [Giveth/giveth-landing-page#28]
Since the interim website is being used longer than intended. I would like to propose changes in the current version: photos and some of the content. 

For Photos, I would like to see something a bit more relevant to the content that follows:
 1) Creating Altruistic Communities : https://images.unsplash.com/photo-1493528237448-144452699e16?ixlib=rb-0.3.5&q=85&fm=jpg&crop=entropy&cs=srgb&dl=vlad-tchompalov-248830.jpg&s=60131faf326635c11a0392311020634a, https://unsplash.com/search/photos/protest?photo=nKNrOZ5MXZY

2) Connecting and Building Trust : https://images.pexels.com/photos/207896/pexels-photo-207896.jpeg?dl&fit=crop&w=1920&h=1018, https://www.pexels.com/photo/adventure-backlit-dawn-dusk-207896/

I would also like to see the comment about 'ICOs' to be removed.

**Comment by 0xgraciegrace** [comment]
![vlad-tchompalov-248830 copy](https://user-images.githubusercontent.com/18598517/29676954-e3673a82-88f9-11e7-913b-ea50c22be4d3.jpg)
![pexels-photo-207896](https://user-images.githubusercontent.com/18598517/29676971-ede571ea-88f9-11e7-8ba6-4505d4c6fe45.jpeg)

**Comment by geleeroyale** [comment]
I'm all for picture01 with the signs. For the second one I am not so sure, but we can go with it, since it is better than the one we have now.

Do you have recommendations for replacing the ICO part? We definitely want to keep the milestonetracker on the feature list.

**Comment by geleeroyale** [comment]
Updated pictures and text ... visible in: https://staging.giveth.io/ ... Please review

**Comment by 0xgraciegrace** [comment]
Hi Kay, thanks for working on this review so fast. I have a couple of suggestions:

1- Instead of Charitable Communities --> Creating Altruistic Communities

2- Replace description of Charitable communities for ---->
Anyone can create a cause on anything they feel strongly about supporting. Whether it is solar energy to impoverished area, or organizing a recycling campaign, they can use the Giveth platform to find other people that share their excitement.  Giveth encourage organized efforts
and shared resources to tackle global and local problems together. The main goal is to cultivate connections that build strong communities upon a solid foundation of transparency and accountability powered by blockchain tech.

2- Instead of Rewards Good People's deed ---> Connecting and Building Trust

3- Last paragraph that had the ICO comment --->
Our milestone contracts once fully tested and they are able to keep organizations and causes accountable to their supporters. Breaking down lump sum amounts and ensuring milestones completion is an approach that can help all types of organizations (for profit or non-profits) as well as the current ICO ecosystem by reassuring that contributed funds are well spent.   

4- Transparent Innovation (Update Content) ---->
Giveth will revolutionize donation giving by fusing smart contract governance systems, and peer to peer community building on social media platforms.
It can be used by NGOs to automate accounting, collect and distribute donated funds, 
provide oversight to projects on a global scale and minimizing intermediaries across the board.
The Dapp is designed to be modular and flexible to allow for permissionless innovation.
Part of that innovation is focusing on incentive structures for independent reviewers to verify the completion of milestones, or Rewarding Volunteers with tokens, badges or even ether
to keep them engaged with the Cause and the Community.

What do you think of the tagline: Giveth - 'the future of charitable giving' - as we end the page with 'Let's build the future of Giving'...??

https://docs.google.com/spreadsheets/d/1yZ4qS2X9UbC799L5UQNQkqIQh-X2b0gZyZCRh4H9Q6I/edit?usp=sharing

**Comment by geleeroyale** [comment]
I second your proposal for changes, the basic text blocks are a great improvement! 

However, there are many typos and errors in the texts. I find myself having to edit so many errors out of texts ..... 

I will edit them out again on the spreadsheet, but it would be great if we could pay more attention to this kind of errors in our text databases before we are submitting new text for review.

**Comment by geleeroyale** [comment]
Changes have been implemented and are ready for review: [staging.giveth.io](http://staging.giveth.io)

**Comment by 0xgraciegrace** [comment]
1) An extra 'M' in the 3 paragraph... 
MMakers create milestones

2) The main goal of Giveth, is, to facilitate these connections,  --- this looks weird. Rephrasing?

**Comment by 0xgraciegrace** [comment]
The web copy has been updated to reflect the current (Aug 28) website content. It is best practice to keep track. 
https://docs.google.com/spreadsheets/d/1yZ4qS2X9UbC799L5UQNQkqIQh-X2b0gZyZCRh4H9Q6I/edit?usp=sharing

The "are you ready?' at the end was removed. Was this something that did not look good?
Also, the statement "Let's build the future of Charitable Giving is missing '!' exclamation point. It loses the emphasis of the statement. 

Lastly, I realise that the "Connect and Build Trust" paragraph does not relate to the photo shown. I guess we still need to search for something else that aligns with the content.

**Comment by geleeroyale** [comment]
Great you spotted those typos, Grace, thanks! Staging has been updated to reflect the changes.

**Comment by geleeroyale** [comment]
For the last picture, I started a collection on unsplash: [https://unsplash.com/collections/1091098/giveth](https://unsplash.com/collections/1091098/giveth)

**Comment by 0xgraciegrace** [comment]
When shall we push these modifications? I would like to start promoting Giveth amongst some selected organisations and would love to see the updates on the website.

**Comment by 0xgraciegrace** [comment]
Also, the statement "Let's build the future of Charitable Giving is missing '!' exclamation point. It loses the emphasis of the statement.
