### ISSUE TITLE
Proposed web copy for final website Oct 2017

### ISSUE THREAD

**Issue by 0xgraciegrace** [Giveth/giveth-landing-page#34]
Using a mixed of existing and new content to create the final website that aims to attract developers. 

https://docs.google.com/document/d/19tpcEfg_q6-NCmtfx9fbWxOwwYAMrFjGT-ERZNFjLIw/edit?usp=sharing

**Comment by geleeroyale** [comment]
As this proposal changes lots of text I would like more people to have a review of the suggested changes: @GriffGreen @krrisis ... Will add comments over the weekend, as well as start to integrate some of these changes.

**Comment by 0xgraciegrace** [comment]
This webcopy is for @alanborger to create a new website. It can then be given to you to host accordingly.

**Comment by geleeroyale** [comment]
This is the old repository. Please post comments and new issues here: https://github.com/giveth/website/issues/
