### ISSUE TITLE
This is the proposed flow and images for the new Giveth website

### ISSUE THREAD

**Issue by 0xgraciegrace** [Giveth/giveth-landing-page#35]
Once the images have been agreed, I will go ahead ad purchase them for Giveth use. If there are other istock image/video that is considered appealing for the website, please let me know.

https://docs.google.com/presentation/d/1CcTvSXXDwZNQiXItN3ixpTciGP6-BEeRuclptX4VcNM/edit?usp=sharing

**Comment by geleeroyale** [comment]
I would go for all the suggested new graphics, as I like the suggestions much better that what we have now (except the mini-me reload icon like explained in comments) ... Please if you can - get them in SVG file format.

**Comment by 0xgraciegrace** [comment]
The images are not available in SVG but I was able to get EPS. I hope you can work with these. I will upload the illustration in the following folder:
Google Drive/Giveth/Website /Website Final Version October 2017/Assets

**Comment by geleeroyale** [comment]
EPS is also great, thank you! Let's see what we have here ...
